### ISSUE TITLE
Semantic HTML elements

### ISSUE THREAD

**Issue by aubreywullschleger** [samueldowd/prj-rev-bwfs-tea-cozy#1]
Great! Awesome job using the semantic HTML elements `<header>`, `<nav>`, and `<footer>`.  Using semantic elements helps improve the accessibility of your page. Here's info on how semantic elements help with accessibility: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide (scroll down to the 'So what are semantic elements good for?' heading) and a list of more semantic elements you can use: http://www.techstrikers.com/HTML5/html5-semantic-elements.php

Example: https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L11-L15

**Comment by samueldowd** [comment]
Fixed in https://github.com/samueldowd/tea-cozy/commit/cfcc53adc53457160794838de6bd44dc3e233b3d
