### ISSUE TITLE
Page navigation

### ISSUE THREAD

**Issue by aubreywullschleger** [samueldowd/prj-rev-bwfs-tea-cozy#2]
Great! I love your page navigation feature that links to different sections of your site.  This feature is great for smooth page navigation and helps with creating a great user experience.

https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L12-L14
https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L17
https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L24
https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L63

Here I would consider making your entire `<header>` element `position: fixed;` so that users can see and navigate the page with it no matter where they are on the page.

**Comment by samueldowd** [comment]
Fixed in https://github.com/samueldowd/tea-cozy/commit/2334f1072ef50b81f34df943fbd70ab7e5661b61
