### ISSUE TITLE
Using locally stored images, and src attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [samueldowd/prj-rev-bwfs-tea-cozy#3]
Great! Nice job using locally stored images for your project! This is best practice for production code and helps your page load faster. 

Example: https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L10

Make sure to use descriptive `alt` attributes on your `<img>` elements, like this: `<img src="resources/images/img-tea-cozy-logo.png" id="logo" alt="tea cozy logo"/>` This is best practice and helps make your site to be even more accessible!  

Also, be sure that you are wrapping your attribute values in quotes throughout your HTML (including your `src` attribute values.)  The `<img>` elements on lines 32-48 do not have quotes around the `src` attribute values.

https://github.com/samueldowd/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/index.html#L32-L48

**Comment by samueldowd** [comment]
Fixed in: https://github.com/samueldowd/tea-cozy/commit/7c4020daeaa2ee3a5846cdb60afda68602c6716d
